In [1]:
A = reshape(1:9, (3,3))

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [6]:
A[A .< 5]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [7]:
A[A .> 5]

4-element Array{Int64,1}:
 6
 7
 8
 9

In [8]:
A[A .== 5]

1-element Array{Int64,1}:
 5

In [9]:
A[3 .< A .<= 7]

4-element Array{Int64,1}:
 4
 5
 6
 7

In [10]:
A = [1, 2, 3]
B = [4, 5, 6]
A + B

3-element Array{Int64,1}:
 5
 7
 9

In [11]:
A .+ [4]

3-element Array{Int64,1}:
 5
 6
 7

In [15]:
A * B

LoadError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  *(::LinearAlgebra.Adjoint{var"#s828",var"#s8281"} where var"#s8281"<:(AbstractArray{T,1} where T) where var"#s828"<:Number, ::AbstractArray{var"#s827",1} where var"#s827"<:Number) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:283
  *(::LinearAlgebra.Transpose{T,var"#s828"} where var"#s828"<:(AbstractArray{T,1} where T), ::AbstractArray{T,1}) where T<:Real at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:284
  ...

In [12]:
A .* B

3-element Array{Int64,1}:
  4
 10
 18

In [14]:
A'

1×3 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 1  2  3